enableColors: true

enableHyperlinks: true

enableProgressBars: true

logFilters:
  - code: YN0013
    level: discard
  - code: YN0000
    level: discard

nmHoistingLimits: workspaces

nodeLinker: node-modules

preferInteractive: true

yarnPath: .yarn/releases/yarn-4.0.2.cjs
